version: '2'

services:
### nginx-proxy ###
  nginx-proxy:
    container_name: nginx-proxy
    image: sig9/nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../mount/nginx-proxy/certs:/etc/nginx/certs:ro
      - ../../mount/nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - ../../mount/nginx-proxy/vhost:/etc/nginx/vhost.d
      - ../../mount/nginx-proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
  letsencrypt-nginx-proxy-companion:
    volumes_from:
      - nginx-proxy
    container_name: letsencrypt-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    #privileged: true
    volumes:
      - ../../mount/nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
