version: '2'

services:

### Gitbucket ###
# 初期パスワード root/root
  gitbucket:
    links:
      - mariadb:mariadb
    container_name: gitbucket
    ports:
      - "29418:29418"
      - "8081:8080"
    environment:
      - VIRTUAL_HOST=gitbucket.*
      # ポートが複数開いている場合は、プロクシするポートを指定する必要あり
      - VIRTUAL_PORT=8080
    image: f99aq8ove/gitbucket
    # /gitbucket/repositories/ 配下にリポジトリができる。例 root/test.git
    volumes:
      - ../../mount/gitbucket:/gitbucket
      # gitリポジトリを参照させるためのVolume。
      - ../../mount/git:/gitbucket/repositories
    command: java -jar /opt/gitbucket.war --prefix=/
    
