version: '2'

services:

### Redmine ###
#初期パスワード admin/admin
  redmine:
    links:
      - mariadb:mariadb
    container_name: redmine
    ports:
      - "8083:80"
    image: sameersbn/redmine:3.3.0-3
    environment:
      - VIRTUAL_HOST=redmine.*
    
      - TZ=Asia/Tokyo
      
      - DB_ADAPTER=mysql2
      - DB_HOST=mariadb
#      - DB_PORT=5432
      - DB_USER=root
      - DB_PASS=admin

      - DB_NAME=redmine
      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=/
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30
    volumes:
      - ../../mount/redmine/redmine:/home/redmine/data
      - ../../mount/redmine/log:/var/log/redmine
      # gitリポジトリを参照するためのVolume。Git側も設定する。
      - ../../mount/git:/git:ro
      
  