version: '2'
services:
    mongo:
      image: mongo
    # volumes:
    #    - ./data/runtime/db:/data/db
    #    - ./data/dump:/dump
      command: mongod --smallfiles --oplogSize 128

    rocketchat:
      image: rocketchat/rocket.chat:latest
      volumes:
        - rocket-data:/app/uploads
      environment:
        - PORT=3000
        - ROOT_URL=http://localhost
        - MONGO_URL=mongodb://mongo:27017/rocketchat
    #    - MAIL_URL=smtp://smtp.email
    #    - HTTP_PROXY=http://proxy.domain.com
    #    - HTTPS_PROXY=http://proxy.domain.com
      links:
        - mongo:mongo
      ports:
        - 80:3000

    # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
    hubot:
      image: rocketchat/hubot-rocketchat:v0.1.4
      environment:
        - ROCKETCHAT_URL=rocketchat
        - ROCKETCHAT_ROOM=GENERAL
        - ROCKETCHAT_USER=bot
        - ROCKETCHAT_PASSWORD=botpassword
        - BOT_NAME=bot
    # you can add more scripts as you'd like here, they need to be installable by npm
        - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
      links:
        - rocketchat:rocketchat
    # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
      ports:
        - 3001:8080

volumes:
  rocket-data:
    driver: local