version: '2'

services:
  
### Jenkins ###
  jenkins:
    container_name: jenkins
    ports:
      - "8082:8080"
    image: jenkins:latest
    environment:
      - VIRTUAL_HOST=jenkins.*
      # ポートが複数開いている場合は、プロクシするポートを指定する必要あり
      - VIRTUAL_PORT=8080
      
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - ../../mount/jenkins-home:/var/jenkins_home
