version: '2'

services:

### owncloud ###
  owncloud:
    links:
      - ownPosgre:postgres
    container_name: owncloud
    image: owncloud
    #privileged: true
    volumes:
      - ../../mount/owncloud/html:/var/www/html
      - ../../mount/owncloud/apps:/var/www/html/apps
      - ../../mount/owncloud/config:/var/www/html/config
      # winで権限を0770にできないためやむなく名前付きボリューム 
      - owncloud-data:/var/www/html/data
    environment:
      VIRTUAL_HOST: owncloud.*
      #LETSENCRYPT_HOST: owncloud.127.0.0.1.xip.io
      #LETSENCRYPT_EMAIL: admin@example.com
      START_MYSQL: 'false'
      TARGET_SUBDIR: /
      
  ownPosgre:
    container_name: ownPosgre
    image: sameersbn/postgresql:9.5-1
    environment:
      - DB_USER=owncloud
      - DB_PASS=password
      - DB_NAME=owncloud
    # dbはwinフォルダにマウントできない。
    volumes:
      - ownPosgre-data:/var/lib/postgresql
      - ownPosgre-run:/run/postgresql
      
volumes:
  ### owncloud ###
  owncloud-data:
  ownPosgre-data:
  ownPosgre-run: