version: '2'

services:

### TestLink ### 
#初期パスワード admin/admin
  testlink:
    container_name: testlink
    image: bitnami/testlink:latest
    ports:
      - '8084:80'
    volumes:
      - ../../mount/testlink/testlink:/bitnami/testlink
      - ../../mount/testlink/apache:/bitnami/apache
    links:
      - mariadb:mariadb
    environment:
      VIRTUAL_HOST: testlink.*
      TESTLINK_USERNAME: admin
      TESTLINK_PASSWORD: admin
      TESTLINK_EMAIL: admin@example.com
      MARIADB_PASSWORD: admin
      

